# Use a lightweight JDK 17 image
FROM eclipse-temurin:17-jre-alpine

# Create an app directory
WORKDIR /app

# Copy the JAR file generated by the Maven build step
# The * helps if the version number in the filename changes
COPY target/*.jar app.jar

# Spring Boot default port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
